on: [push, pull_request]
jobs:
  zadanie:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - run: g++ 0212.cpp -o 0212
    - run: ./0212
    - run: ./0212
